theme="material-design"
baseurl = "https://staminaloops.github.io/undefinedisnotafunction/"
languageCode = "en-us"
title = "Undefined is not a function"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
disqusShortname = "staminaloops" # optional
copyright = "2016 staminaloops"

[params]
  description = "Things about JavaScript things, front-end things and other things." # optional
  twitter = "staminaloops" # optional
  github = "staminaloops" # optional
  # optionalbfacebook = "Your facebook Name" # optional
  # optional gplus = "Your Google+ profile name" # optional
  # optional linkedin = "Your LinkedIn Name" # optional
  headerCover = "images/header.png" # optional
  googleAnalyticsUserID = "UA-71795144-3" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
